# Project: ParseTree
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = src/main.o src/compiler/backend/backend.o src/compiler/node/node.o src/compiler/token/index.o src/compiler/token/delimiter/delimiter_token.o src/compiler/token/end_of_file/end_of_file_token.o src/compiler/token/identifier/identifier_token.o src/compiler/token/integer/integer_token.o src/compiler/token/keyword/keyword_token.o src/compiler/token/operator/operator_token.o src/compiler/token/token_type_id/token_type_id.o
LINKOBJ  = src/main.o src/compiler/backend/backend.o src/compiler/node/node.o src/compiler/token/index.o src/compiler/token/delimiter/delimiter_token.o src/compiler/token/end_of_file/end_of_file_token.o src/compiler/token/identifier/identifier_token.o src/compiler/token/integer/integer_token.o src/compiler/token/keyword/keyword_token.o src/compiler/token/operator/operator_token.o src/compiler/token/token_type_id/token_type_id.o
LIBS     = -L"C:/MinGW/lib" -L"C:/MinGW/x86_64-w64-mingw32/lib" -static-libstdc++ -static-libgcc -std=c++17
INCS     = -I"C:/MinGW/include" -I"C:/MinGW/x86_64-w64-mingw32/include" -I"C:/MinGW/lib/gcc/x86_64-w64-mingw32/11.2.0/include"
CXXINCS  = -I"C:/MinGW/include" -I"C:/MinGW/x86_64-w64-mingw32/include" -I"C:/MinGW/lib/gcc/x86_64-w64-mingw32/11.2.0/include"
BIN      = ParseTree.exe
CXXFLAGS = $(CXXINCS) -std=gnu++11
CFLAGS   = $(INCS) -std=gnu++11
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

src/main.o: src/main.cpp
	$(CPP) -c src/main.cpp -o src/main.o $(CXXFLAGS)

src/compiler/backend/backend.o: src/compiler/backend/backend.cpp
	$(CPP) -c src/compiler/backend/backend.cpp -o src/compiler/backend/backend.o $(CXXFLAGS)

src/compiler/node/node.o: src/compiler/node/node.cpp
	$(CPP) -c src/compiler/node/node.cpp -o src/compiler/node/node.o $(CXXFLAGS)

src/compiler/token/index.o: src/compiler/token/index.cpp
	$(CPP) -c src/compiler/token/index.cpp -o src/compiler/token/index.o $(CXXFLAGS)

src/compiler/token/delimiter/delimiter_token.o: src/compiler/token/delimiter/delimiter_token.cpp
	$(CPP) -c src/compiler/token/delimiter/delimiter_token.cpp -o src/compiler/token/delimiter/delimiter_token.o $(CXXFLAGS)

src/compiler/token/end_of_file/end_of_file_token.o: src/compiler/token/end_of_file/end_of_file_token.cpp
	$(CPP) -c src/compiler/token/end_of_file/end_of_file_token.cpp -o src/compiler/token/end_of_file/end_of_file_token.o $(CXXFLAGS)

src/compiler/token/identifier/identifier_token.o: src/compiler/token/identifier/identifier_token.cpp
	$(CPP) -c src/compiler/token/identifier/identifier_token.cpp -o src/compiler/token/identifier/identifier_token.o $(CXXFLAGS)

src/compiler/token/integer/integer_token.o: src/compiler/token/integer/integer_token.cpp
	$(CPP) -c src/compiler/token/integer/integer_token.cpp -o src/compiler/token/integer/integer_token.o $(CXXFLAGS)

src/compiler/token/keyword/keyword_token.o: src/compiler/token/keyword/keyword_token.cpp
	$(CPP) -c src/compiler/token/keyword/keyword_token.cpp -o src/compiler/token/keyword/keyword_token.o $(CXXFLAGS)

src/compiler/token/operator/operator_token.o: src/compiler/token/operator/operator_token.cpp
	$(CPP) -c src/compiler/token/operator/operator_token.cpp -o src/compiler/token/operator/operator_token.o $(CXXFLAGS)

src/compiler/token/token_type_id/token_type_id.o: src/compiler/token/token_type_id/token_type_id.cpp
	$(CPP) -c src/compiler/token/token_type_id/token_type_id.cpp -o src/compiler/token/token_type_id/token_type_id.o $(CXXFLAGS)
